on: pull_request
name: Linters
env:
  FORCE_COLOR: 1
jobs:
  rubocop:
    name: Rubocop
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7.0
      - name: Setup Rubocop
        run: |
          gem install --no-document rubocop:'~>0.91.0'
      - name: Rubocop Report
        run: rubocop --color